EQLB-216 - Add RemoveAccent field
enjoei/pkg pull request #9
Opened 2021-09-10 13:36 UTC by matsales28

2021-09-10 14:41 UTC, guilhermecoltro requested changes

2021-09-10 14:41 UTC, guilhermecoltro commented on querybuilder/rule.go
> +	RemoveAccent bool
Maninho, vocês estão utilizando o VS Code? Se sim, a própria extensão do GO deveria ter formatado essa struct pra todas as props/types serem formatados na hora em que o arquivo foi salvo... Se não formatou pode ser que tenha algum errinho de síntaxe no arquivo

2021-09-10 14:41 UTC, guilhermecoltro commented on querybuilder/rule.go
> +		return *removeAccents(&v)
Aqui acho que tem 2 pontos:
- Essa função retorna uma interface{} que é o "tipo genérico" em Go, só que não é muito recomendado fazer esse tipo de retorno porque muitas vezes a gente pode perder o controle sobre esse código por não saber de fato o que aquela função pode retornar... Seria possível fazer essa função retornar um tipo de fato ao invés de retornar um genérico?
- Vi que essa função de removeAccents recebe um ponteiro, trabalha com esse ponteiro dentro dela e retorna um ponteiro, por isso pra chamar ela você retorna com o próprio ponteiro, só que ao meu ver fica um pouco confuso de ler o código dessa forma, uma vez que a ideia dessa função seria apenas receber uma string, remover os acentos e retornar uma string (ao invés de receber ponteiro e retornar ponteiro)... Outro problema gerado em cima disso é que pelo fato de você trabalhar com ponteiro aqui muitas vezes você pode acabar, sem querer, alterando a variável original. Seria muito complexo alterar essa função para receber string e retornar string e não utilizar ponteiro?

2021-09-10 14:41 UTC, guilhermecoltro commented on querybuilder/rule_group.go
> +		r.RemoveAccent = rule["remove_accents"].(bool)
Essa função aqui recebe um mapa do tipo string -> genérico, certo?
Será que não era válido já fazer ela receber o tipo rule mesmo por padrão?
Ai você fugiria do uso do genérico. Quando a gente usa o genérico no Go a gente perde muito do poder da tipagem dele que facilita no código

2021-09-10 15:22 UTC, guilhermecoltro approved these changes

2021-09-10 18:29 UTC, talesmantovani approved these changes

2021-09-10 19:07 UTC, caiobsilva approved these changes

2021-09-15 12:22 UTC, cassianoblonski approved these changes

2021-09-20 13:29 UTC, merged